name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.0.0

      - name: Check code formatting
        run: deno fmt --check

      - name: Check code linting
        run: deno lint

      - name: Check types
        run: deno check **/*.ts && deno check **/*.tsx

      - name: Run tests
        run: deno test --allow-net --allow-read --allow-import
